// Book Cover Template Definitions for BizFlip
// Each cover template has a unique visual style for the front cover of the digital book

export type CoverCategory = 'luxury' | 'minimal' | 'modern' | 'editorial' | 'classic' | 'creative';

export interface CoverTemplateStyle {
  id: string;
  name: string;
  label: string;
  description: string;
  category: CoverCategory;
  categoryLabel: string;
  // Visual config for rendering the cover preview
  style: {
    bg: string;
    bgGradient?: string;
    textColor: string;
    accentColor: string;
    titleFont: string;
    subtitleFont: string;
    tagName: string;
    tagStyle: 'gold-line' | 'gold-badge' | 'underline' | 'dot' | 'none' | 'outline-badge';
    coverImagePosition: 'top' | 'center' | 'bottom' | 'full' | 'none' | 'left-third';
    coverImageShape: 'full' | 'rounded' | 'circle' | 'arch' | 'contained';
    decorativeElements: string[];
    overlay: 'none' | 'dark-gradient' | 'light-gradient' | 'solid-bottom' | 'vignette';
    buttonStyle: 'gold-pill' | 'outline' | 'ghost' | 'solid-dark' | 'filled-accent';
    buttonLabel: string;
    cornerStyle: 'sharp' | 'rounded' | 'pill';
    borderStyle: 'none' | 'gold-line' | 'double-line' | 'thin-line';
    pattern: 'none' | 'diamonds' | 'dots' | 'lines' | 'geometric';
  };
  recommendedFor: string[];
}

export const COVER_CATEGORIES: { id: CoverCategory; label: string; icon: string }[] = [
  { id: 'luxury', label: 'Luxury', icon: '✦' },
  { id: 'minimal', label: 'Minimal', icon: '○' },
  { id: 'modern', label: 'Modern', icon: '◈' },
  { id: 'editorial', label: 'Editorial', icon: '§' },
  { id: 'classic', label: 'Classic', icon: '❖' },
  { id: 'creative', label: 'Creative', icon: '✧' },
];

export const COVER_TEMPLATES: CoverTemplateStyle[] = [
  // ═══════════════════════════════════════════
  // LUXURY — Elegant, premium and sophisticated
  // ═══════════════════════════════════════════
  {
    id: 'aurelia',
    name: 'aurelia',
    label: 'AURELIA',
    description: 'Elegant gold-accented luxury cover with refined typography',
    category: 'luxury',
    categoryLabel: 'Luxury',
    style: {
      bg: '#0C0A09',
      bgGradient: 'linear-gradient(165deg, #0C0A09 0%, #1C1917 50%, #0C0A09 100%)',
      textColor: '#FAFAF9',
      accentColor: '#C9A84C',
      titleFont: 'serif',
      subtitleFont: 'sans',
      tagName: 'Signature Menu',
      tagStyle: 'gold-line',
      coverImagePosition: 'top',
      coverImageShape: 'arch',
      decorativeElements: ['gold-line-divider', 'corner-ornament'],
      overlay: 'dark-gradient',
      buttonStyle: 'gold-pill',
      buttonLabel: 'Tap to Open',
      cornerStyle: 'sharp',
      borderStyle: 'gold-line',
      pattern: 'diamonds',
    },
    recommendedFor: ['Restaurant', 'Hotel', 'Fine Dining', 'Bar'],
  },
  {
    id: 'royale',
    name: 'royale',
    label: 'ROYALE',
    description: 'Regal deep navy with champagne gold accents',
    category: 'luxury',
    categoryLabel: 'Luxury',
    style: {
      bg: '#0F172A',
      bgGradient: 'linear-gradient(145deg, #0F172A 0%, #1E293B 60%, #0F172A 100%)',
      textColor: '#F8FAFC',
      accentColor: '#D4AF37',
      titleFont: 'serif',
      subtitleFont: 'sans',
      tagName: 'Premium Collection',
      tagStyle: 'outline-badge',
      coverImagePosition: 'center',
      coverImageShape: 'rounded',
      decorativeElements: ['crown-ornament', 'gold-rule'],
      overlay: 'vignette',
      buttonStyle: 'gold-pill',
      buttonLabel: 'Discover',
      cornerStyle: 'rounded',
      borderStyle: 'double-line',
      pattern: 'none',
    },
    recommendedFor: ['Hotel', 'Fine Dining', 'Bar', 'Bakery'],
  },
  {
    id: 'imperial',
    name: 'imperial',
    label: 'IMPERIAL',
    description: 'Grand imperial design with rich burgundy tones',
    category: 'luxury',
    categoryLabel: 'Luxury',
    style: {
      bg: '#1A0A0A',
      bgGradient: 'linear-gradient(180deg, #1A0A0A 0%, #2D1010 50%, #1A0A0A 100%)',
      textColor: '#FEF2F2',
      accentColor: '#B8860B',
      titleFont: 'serif',
      subtitleFont: 'sans',
      tagName: 'The Collection',
      tagStyle: 'gold-line',
      coverImagePosition: 'full',
      coverImageShape: 'full',
      decorativeElements: ['imperial-border', 'gold-corners'],
      overlay: 'dark-gradient',
      buttonStyle: 'outline',
      buttonLabel: 'Open Menu',
      cornerStyle: 'sharp',
      borderStyle: 'double-line',
      pattern: 'geometric',
    },
    recommendedFor: ['Hotel', 'Fine Dining', 'Catering', 'Restaurant'],
  },
  {
    id: 'elite',
    name: 'elite',
    label: 'ÉLITE',
    description: 'Sleek black with platinum accents for the discerning brand',
    category: 'luxury',
    categoryLabel: 'Luxury',
    style: {
      bg: '#09090B',
      bgGradient: 'linear-gradient(135deg, #09090B 0%, #18181B 50%, #09090B 100%)',
      textColor: '#FAFAFA',
      accentColor: '#A1A1AA',
      titleFont: 'sans',
      subtitleFont: 'sans',
      tagName: 'Exclusive',
      tagStyle: 'dot',
      coverImagePosition: 'top',
      coverImageShape: 'contained',
      decorativeElements: ['thin-rule', 'corner-marks'],
      overlay: 'none',
      buttonStyle: 'ghost',
      buttonLabel: 'Explore',
      cornerStyle: 'sharp',
      borderStyle: 'thin-line',
      pattern: 'lines',
    },
    recommendedFor: ['Fashion', 'Real Estate', 'Salon', 'Café'],
  },

  // ═══════════════════════════════════════════
  // MINIMAL — Clean and simple
  // ═══════════════════════════════════════════
  {
    id: 'pure',
    name: 'pure',
    label: 'PURE',
    description: 'Pure white canvas with subtle charcoal text',
    category: 'minimal',
    categoryLabel: 'Minimal',
    style: {
      bg: '#FAFAF9',
      bgGradient: undefined,
      textColor: '#1C1917',
      accentColor: '#1C1917',
      titleFont: 'sans',
      subtitleFont: 'sans',
      tagName: 'Menu',
      tagStyle: 'underline',
      coverImagePosition: 'center',
      coverImageShape: 'rounded',
      decorativeElements: ['thin-rule'],
      overlay: 'none',
      buttonStyle: 'solid-dark',
      buttonLabel: 'Open',
      cornerStyle: 'rounded',
      borderStyle: 'thin-line',
      pattern: 'none',
    },
    recommendedFor: ['Café', 'Bakery', 'Salon', 'Restaurant'],
  },
  {
    id: 'mono',
    name: 'mono',
    label: 'MONO',
    description: 'True monochrome with black, white, and nothing else',
    category: 'minimal',
    categoryLabel: 'Minimal',
    style: {
      bg: '#FFFFFF',
      bgGradient: undefined,
      textColor: '#0A0A0A',
      accentColor: '#0A0A0A',
      titleFont: 'sans',
      subtitleFont: 'mono',
      tagName: 'EST.',
      tagStyle: 'dot',
      coverImagePosition: 'top',
      coverImageShape: 'full',
      decorativeElements: ['bold-rule'],
      overlay: 'none',
      buttonStyle: 'solid-dark',
      buttonLabel: 'View Menu',
      cornerStyle: 'sharp',
      borderStyle: 'none',
      pattern: 'none',
    },
    recommendedFor: ['Café', 'Fashion', 'Creative Agency', 'Bakery'],
  },
  {
    id: 'essential',
    name: 'essential',
    label: 'ESSENTIAL',
    description: 'Only the essentials — clean layout, clear hierarchy',
    category: 'minimal',
    categoryLabel: 'Minimal',
    style: {
      bg: '#FAFAF9',
      bgGradient: undefined,
      textColor: '#292524',
      accentColor: '#78716C',
      titleFont: 'sans',
      subtitleFont: 'sans',
      tagName: 'Our Menu',
      tagStyle: 'underline',
      coverImagePosition: 'center',
      coverImageShape: 'rounded',
      decorativeElements: ['dot-separator'],
      overlay: 'none',
      buttonStyle: 'outline',
      buttonLabel: 'Browse',
      cornerStyle: 'rounded',
      borderStyle: 'none',
      pattern: 'none',
    },
    recommendedFor: ['Restaurant', 'Café', 'Food Truck', 'Fast Food'],
  },
  {
    id: 'whitespace',
    name: 'whitespace',
    label: 'WHITESPACE',
    description: 'Maximum breathing room for a serene presentation',
    category: 'minimal',
    categoryLabel: 'Minimal',
    style: {
      bg: '#F5F5F4',
      bgGradient: undefined,
      textColor: '#1C1917',
      accentColor: '#A8A29E',
      titleFont: 'serif',
      subtitleFont: 'sans',
      tagName: 'Menu',
      tagStyle: 'none',
      coverImagePosition: 'none',
      coverImageShape: 'full',
      decorativeElements: [],
      overlay: 'none',
      buttonStyle: 'outline',
      buttonLabel: 'Open',
      cornerStyle: 'pill',
      borderStyle: 'none',
      pattern: 'none',
    },
    recommendedFor: ['Salon', 'Spa', 'Yoga', 'Wellness'],
  },

  // ═══════════════════════════════════════════
  // MODERN — Contemporary technology-inspired
  // ═══════════════════════════════════════════
  {
    id: 'nexus',
    name: 'nexus',
    label: 'NEXUS',
    description: 'Futuristic dark theme with cyan electric accents',
    category: 'modern',
    categoryLabel: 'Modern',
    style: {
      bg: '#0A0A0F',
      bgGradient: 'linear-gradient(160deg, #0A0A0F 0%, #12121A 50%, #0A0A0F 100%)',
      textColor: '#E4E4E7',
      accentColor: '#22D3EE',
      titleFont: 'sans',
      subtitleFont: 'mono',
      tagName: 'DIGITAL MENU',
      tagStyle: 'outline-badge',
      coverImagePosition: 'center',
      coverImageShape: 'rounded',
      decorativeElements: ['grid-overlay', 'glow-dot'],
      overlay: 'none',
      buttonStyle: 'filled-accent',
      buttonLabel: 'Launch',
      cornerStyle: 'rounded',
      borderStyle: 'thin-line',
      pattern: 'dots',
    },
    recommendedFor: ['Creative Agency', 'Technology', 'Real Estate', 'Fast Food'],
  },
  {
    id: 'form',
    name: 'form',
    label: 'FORM',
    description: 'Structured geometric layout with bold accents',
    category: 'modern',
    categoryLabel: 'Modern',
    style: {
      bg: '#FAFAFA',
      bgGradient: undefined,
      textColor: '#18181B',
      accentColor: '#6366F1',
      titleFont: 'sans',
      subtitleFont: 'sans',
      tagName: 'MENU',
      tagStyle: 'gold-badge',
      coverImagePosition: 'left-third',
      coverImageShape: 'full',
      decorativeElements: ['geometric-block', 'color-bar'],
      overlay: 'none',
      buttonStyle: 'solid-dark',
      buttonLabel: 'View',
      cornerStyle: 'sharp',
      borderStyle: 'none',
      pattern: 'geometric',
    },
    recommendedFor: ['Real Estate', 'Creative Agency', 'Fashion', 'Technology'],
  },
  {
    id: 'modern-cover',
    name: 'modern-cover',
    label: 'MODERN',
    description: 'Clean contemporary design with smart typography',
    category: 'modern',
    categoryLabel: 'Modern',
    style: {
      bg: '#18181B',
      bgGradient: 'linear-gradient(180deg, #18181B 0%, #27272A 100%)',
      textColor: '#FAFAFA',
      accentColor: '#F97316',
      titleFont: 'sans',
      subtitleFont: 'sans',
      tagName: 'Our Offerings',
      tagStyle: 'underline',
      coverImagePosition: 'top',
      coverImageShape: 'contained',
      decorativeElements: ['accent-bar', 'thin-rule'],
      overlay: 'light-gradient',
      buttonStyle: 'filled-accent',
      buttonLabel: 'Tap to Open',
      cornerStyle: 'rounded',
      borderStyle: 'none',
      pattern: 'none',
    },
    recommendedFor: ['Restaurant', 'Fast Food', 'Food Truck', 'Catering'],
  },
  {
    id: 'grid',
    name: 'grid',
    label: 'GRID',
    description: 'Structured grid-based layout for organized brands',
    category: 'modern',
    categoryLabel: 'Modern',
    style: {
      bg: '#F9FAFB',
      bgGradient: undefined,
      textColor: '#111827',
      accentColor: '#3B82F6',
      titleFont: 'sans',
      subtitleFont: 'mono',
      tagName: 'CATALOG',
      tagStyle: 'outline-badge',
      coverImagePosition: 'top',
      coverImageShape: 'full',
      decorativeElements: ['grid-lines', 'corner-brackets'],
      overlay: 'none',
      buttonStyle: 'solid-dark',
      buttonLabel: 'Browse',
      cornerStyle: 'sharp',
      borderStyle: 'thin-line',
      pattern: 'lines',
    },
    recommendedFor: ['Retail', 'Real Estate', 'Creative Agency', 'Technology'],
  },

  // ═══════════════════════════════════════════
  // EDITORIAL — Magazine and premium publication
  // ═══════════════════════════════════════════
  {
    id: 'editor',
    name: 'editor',
    label: 'EDITOR',
    description: 'Premium magazine-style cover with bold headlines',
    category: 'editorial',
    categoryLabel: 'Editorial',
    style: {
      bg: '#FFFFFF',
      bgGradient: undefined,
      textColor: '#DC2626',
      accentColor: '#DC2626',
      titleFont: 'serif',
      subtitleFont: 'serif',
      tagName: 'THE ISSUE',
      tagStyle: 'gold-line',
      coverImagePosition: 'full',
      coverImageShape: 'full',
      decorativeElements: ['headline-bar', 'issue-number'],
      overlay: 'solid-bottom',
      buttonStyle: 'solid-dark',
      buttonLabel: 'Read Now',
      cornerStyle: 'sharp',
      borderStyle: 'none',
      pattern: 'none',
    },
    recommendedFor: ['Fashion', 'Restaurant', 'Creative Agency', 'Café'],
  },
  {
    id: 'culture',
    name: 'culture',
    label: 'CULTURE',
    description: 'Cultural editorial design with warm earth tones',
    category: 'editorial',
    categoryLabel: 'Editorial',
    style: {
      bg: '#FDF6E3',
      bgGradient: undefined,
      textColor: '#5C4033',
      accentColor: '#8B6914',
      titleFont: 'serif',
      subtitleFont: 'serif',
      tagName: 'FEATURE',
      tagStyle: 'gold-badge',
      coverImagePosition: 'top',
      coverImageShape: 'full',
      decorativeElements: ['editorial-rule', 'column-line'],
      overlay: 'light-gradient',
      buttonStyle: 'outline',
      buttonLabel: 'Explore',
      cornerStyle: 'sharp',
      borderStyle: 'thin-line',
      pattern: 'none',
    },
    recommendedFor: ['Restaurant', 'Hotel', 'Café', 'Cultural'],
  },
  {
    id: 'studio',
    name: 'studio',
    label: 'STUDIO',
    description: 'Creative studio aesthetic with bold layout blocks',
    category: 'editorial',
    categoryLabel: 'Editorial',
    style: {
      bg: '#FEFCE8',
      bgGradient: undefined,
      textColor: '#1A1A1A',
      accentColor: '#CA8A04',
      titleFont: 'sans',
      subtitleFont: 'serif',
      tagName: 'NO. 01',
      tagStyle: 'dot',
      coverImagePosition: 'center',
      coverImageShape: 'rounded',
      decorativeElements: ['color-block', 'number-badge'],
      overlay: 'none',
      buttonStyle: 'solid-dark',
      buttonLabel: 'Open',
      cornerStyle: 'rounded',
      borderStyle: 'none',
      pattern: 'dots',
    },
    recommendedFor: ['Fashion', 'Creative Agency', 'Salon', 'Photography'],
  },
  {
    id: 'signature',
    name: 'signature',
    label: 'SIGNATURE',
    description: 'Personal signature style with elegant script touches',
    category: 'editorial',
    categoryLabel: 'Editorial',
    style: {
      bg: '#1C1917',
      bgGradient: 'linear-gradient(170deg, #1C1917 0%, #292524 100%)',
      textColor: '#F5F5F4',
      accentColor: '#D4C5A9',
      titleFont: 'serif',
      subtitleFont: 'sans',
      tagName: 'EST. 2024',
      tagStyle: 'gold-line',
      coverImagePosition: 'center',
      coverImageShape: 'circle',
      decorativeElements: ['signature-line', 'ornamental-divider'],
      overlay: 'dark-gradient',
      buttonStyle: 'gold-pill',
      buttonLabel: 'View Collection',
      cornerStyle: 'rounded',
      borderStyle: 'gold-line',
      pattern: 'none',
    },
    recommendedFor: ['Fashion', 'Hotel', 'Jewelry', 'Salon'],
  },

  // ═══════════════════════════════════════════
  // CLASSIC — Traditional premium book designs
  // ═══════════════════════════════════════════
  {
    id: 'heritage',
    name: 'heritage',
    label: 'HERITAGE',
    description: 'Time-worn vintage aesthetic with parchment textures',
    category: 'classic',
    categoryLabel: 'Classic',
    style: {
      bg: '#F5E6D0',
      bgGradient: undefined,
      textColor: '#3D2B1F',
      accentColor: '#8B4513',
      titleFont: 'serif',
      subtitleFont: 'serif',
      tagName: 'Since 2024',
      tagStyle: 'gold-line',
      coverImagePosition: 'top',
      coverImageShape: 'arch',
      decorativeElements: ['ornamental-border', 'vintage-divider'],
      overlay: 'none',
      buttonStyle: 'outline',
      buttonLabel: 'Open',
      cornerStyle: 'rounded',
      borderStyle: 'double-line',
      pattern: 'none',
    },
    recommendedFor: ['Hotel', 'Restaurant', 'Bakery', 'Bar'],
  },
  {
    id: 'classic-cover',
    name: 'classic-cover',
    label: 'CLASSIC',
    description: 'Traditional book design with embossed-style elements',
    category: 'classic',
    categoryLabel: 'Classic',
    style: {
      bg: '#1E3A5F',
      bgGradient: 'linear-gradient(180deg, #1E3A5F 0%, #15294A 100%)',
      textColor: '#F0E6D3',
      accentColor: '#D4AF37',
      titleFont: 'serif',
      subtitleFont: 'serif',
      tagName: 'The Menu',
      tagStyle: 'gold-line',
      coverImagePosition: 'center',
      coverImageShape: 'contained',
      decorativeElements: ['embossed-frame', 'gold-ornament'],
      overlay: 'vignette',
      buttonStyle: 'gold-pill',
      buttonLabel: 'Open Menu',
      cornerStyle: 'sharp',
      borderStyle: 'gold-line',
      pattern: 'none',
    },
    recommendedFor: ['Restaurant', 'Hotel', 'Bar', 'Fine Dining'],
  },
  {
    id: 'grand',
    name: 'grand',
    label: 'GRAND',
    description: 'Magnificent cover design with ornate details',
    category: 'classic',
    categoryLabel: 'Classic',
    style: {
      bg: '#2C1810',
      bgGradient: 'linear-gradient(145deg, #2C1810 0%, #3D2416 60%, #2C1810 100%)',
      textColor: '#F5E6D3',
      accentColor: '#C9A84C',
      titleFont: 'serif',
      subtitleFont: 'sans',
      tagName: 'Grand Edition',
      tagStyle: 'gold-badge',
      coverImagePosition: 'top',
      coverImageShape: 'full',
      decorativeElements: ['ornate-frame', 'gold-inner-border'],
      overlay: 'dark-gradient',
      buttonStyle: 'gold-pill',
      buttonLabel: 'Enter',
      cornerStyle: 'sharp',
      borderStyle: 'double-line',
      pattern: 'diamonds',
    },
    recommendedFor: ['Hotel', 'Fine Dining', 'Catering', 'Restaurant'],
  },
  {
    id: 'timeless',
    name: 'timeless',
    label: 'TIMELESS',
    description: 'Elegant and enduring design that never goes out of style',
    category: 'classic',
    categoryLabel: 'Classic',
    style: {
      bg: '#FEFCF3',
      bgGradient: undefined,
      textColor: '#2C2418',
      accentColor: '#6B5B3E',
      titleFont: 'serif',
      subtitleFont: 'serif',
      tagName: 'Timeless',
      tagStyle: 'underline',
      coverImagePosition: 'center',
      coverImageShape: 'rounded',
      decorativeElements: ['simple-rule', 'ornamental-dot'],
      overlay: 'none',
      buttonStyle: 'outline',
      buttonLabel: 'Discover',
      cornerStyle: 'rounded',
      borderStyle: 'thin-line',
      pattern: 'none',
    },
    recommendedFor: ['Hotel', 'Restaurant', 'Bakery', 'Café'],
  },

  // ═══════════════════════════════════════════
  // CREATIVE — Expressive designs for unique brands
  // ═══════════════════════════════════════════
  {
    id: 'art',
    name: 'art',
    label: 'ART',
    description: 'Artistic expression with bold colors and asymmetric layout',
    category: 'creative',
    categoryLabel: 'Creative',
    style: {
      bg: '#FFF7ED',
      bgGradient: 'linear-gradient(135deg, #FFF7ED 0%, #FEF3C7 100%)',
      textColor: '#92400E',
      accentColor: '#EA580C',
      titleFont: 'serif',
      subtitleFont: 'sans',
      tagName: 'CREATE',
      tagStyle: 'gold-badge',
      coverImagePosition: 'left-third',
      coverImageShape: 'full',
      decorativeElements: ['paint-splash', 'color-blob'],
      overlay: 'none',
      buttonStyle: 'filled-accent',
      buttonLabel: 'Explore',
      cornerStyle: 'rounded',
      borderStyle: 'none',
      pattern: 'dots',
    },
    recommendedFor: ['Creative Agency', 'Fashion', 'Art Gallery', 'Photography'],
  },
  {
    id: 'vision',
    name: 'vision',
    label: 'VISION',
    description: 'Dreamy gradient cover with ethereal visual effects',
    category: 'creative',
    categoryLabel: 'Creative',
    style: {
      bg: '#0F0F23',
      bgGradient: 'linear-gradient(160deg, #0F0F23 0%, #1A1A3E 30%, #2D1B69 60%, #0F0F23 100%)',
      textColor: '#EDE9FE',
      accentColor: '#A78BFA',
      titleFont: 'sans',
      subtitleFont: 'sans',
      tagName: 'VISION',
      tagStyle: 'outline-badge',
      coverImagePosition: 'full',
      coverImageShape: 'full',
      decorativeElements: ['glow-circle', 'star-particles'],
      overlay: 'none',
      buttonStyle: 'filled-accent',
      buttonLabel: 'Experience',
      cornerStyle: 'pill',
      borderStyle: 'none',
      pattern: 'none',
    },
    recommendedFor: ['Creative Agency', 'Technology', 'Fashion', 'Photography'],
  },
  {
    id: 'motion',
    name: 'motion',
    label: 'MOTION',
    description: 'Dynamic energy with bold movement and contrast',
    category: 'creative',
    categoryLabel: 'Creative',
    style: {
      bg: '#0A0A0A',
      bgGradient: 'linear-gradient(135deg, #0A0A0A 0%, #1A0A00 50%, #0A0A0A 100%)',
      textColor: '#FFFFFF',
      accentColor: '#FF4500',
      titleFont: 'sans',
      subtitleFont: 'mono',
      tagName: 'MOTION',
      tagStyle: 'outline-badge',
      coverImagePosition: 'center',
      coverImageShape: 'rounded',
      decorativeElements: ['speed-lines', 'accent-slash'],
      overlay: 'none',
      buttonStyle: 'filled-accent',
      buttonLabel: 'Go',
      cornerStyle: 'sharp',
      borderStyle: 'none',
      pattern: 'lines',
    },
    recommendedFor: ['Creative Agency', 'Fast Food', 'Food Truck', 'Technology'],
  },
  {
    id: 'creative-cover',
    name: 'creative-cover',
    label: 'CREATIVE',
    description: 'Unique and expressive for brands that stand out',
    category: 'creative',
    categoryLabel: 'Creative',
    style: {
      bg: '#FFFBEB',
      bgGradient: 'linear-gradient(180deg, #FFFBEB 0%, #FEF3C7 100%)',
      textColor: '#1C1917',
      accentColor: '#D97706',
      titleFont: 'sans',
      subtitleFont: 'serif',
      tagName: 'CREATIVE',
      tagStyle: 'gold-badge',
      coverImagePosition: 'top',
      coverImageShape: 'rounded',
      decorativeElements: ['squiggle', 'color-bar'],
      overlay: 'none',
      buttonStyle: 'solid-dark',
      buttonLabel: 'See Inside',
      cornerStyle: 'rounded',
      borderStyle: 'thin-line',
      pattern: 'dots',
    },
    recommendedFor: ['Creative Agency', 'Fashion', 'Salon', 'Bakery'],
  },
];

// Get recommended templates for a business category
export function getRecommendedCovers(businessCategory: string): CoverTemplateStyle[] {
  return COVER_TEMPLATES.filter((t) =>
    t.recommendedFor.some((r) => r.toLowerCase() === businessCategory.toLowerCase())
  );
}

// Get templates by category
export function getCoversByCategory(category: CoverCategory): CoverTemplateStyle[] {
  return COVER_TEMPLATES.filter((t) => t.category === category);
}

// Search templates
export function searchCovers(query: string): CoverTemplateStyle[] {
  const q = query.toLowerCase().trim();
  if (!q) return COVER_TEMPLATES;
  return COVER_TEMPLATES.filter(
    (t) =>
      t.name.toLowerCase().includes(q) ||
      t.label.toLowerCase().includes(q) ||
      t.description.toLowerCase().includes(q) ||
      t.category.toLowerCase().includes(q) ||
      t.categoryLabel.toLowerCase().includes(q)
  );
}
